<?php namespace ProcessWire;

/**
 * Simple overview list of configured media libraries
 */

class ProcessMediaLibraries extends Process {
	public static function getModuleInfo() {
		return array(
			"title"			=>	"Media Library Overview",
			"summary"		=>	"Display overview of media libraries in admin",
			"version"		=>	"0.1.0",
		);
	}

	public function execute() {
		
		$wrap = new InputfieldWrapper();
		$wrap->attr('id', "MediaLibrariesWrap");
		$wrap->addClass("WireTab");
		$wrap->label = $this->_("Media Libraries Overview");
		
		$mrk = $this->modules->get("InputfieldMarkup");
		$mrk->attr('id', 'MediaLibrariesTableMarkup');
		
		$tbl = $this->modules->get("MarkupAdminDataTable");
		$tbl->setEncodeEntities(false);
		
		$tbl->headerRow(array(
			$this->_("Media Page"),
			$this->_("Path"),
			$this->_("Images"),
			$this->_("Files")
		));
		
		$adminUrl = $this->config->urls->admin;
		foreach($this->pages->find("template=MediaLibrary") as $pg) {
			$tbl->row(array(
				"<a href='{$pg->editURL}'>{$pg->title}</a>",
				implode(' / ', array_map(function($item) use($adminUrl) { return "<a href='{$adminUrl}page/?open=$item->id'>$item->title</a>"; }, $pg->parents()->getArray())),
				$pg->MediaImages ? $pg->MediaImages->count() : 0,
				$pg->MediaFiles ? $pg->MediaFiles->count() : 0
			));
		}
		
		$mrk->value = $tbl->render();
		
		$wrap->append($mrk);
		
		if(! $this->templateExists()) {
			$f = $this->modules->get("InputfieldMarkup");
			$f->attr('id', 'MediaLibrariesProblemMarkup');
			$f->value = '<p>' . $this->_("MediaLibrary template missing. You may need to install/re-install the MediaLibrary module.") . '</p>';
		} else {
			$f = $this->modules->get("InputfieldButton");
			$f->attr('id+name', 'AddMediaLibrary');
			$f->attr('value', $this->_("Add Library"));
			$f->attr('href', $this->page->url . 'add');
			$f->icon = 'plus';
			$f->addClass('head_button_clone');
		}
				
		return $wrap->render() . "<div style='padding: 5px;'>" . $f->render() . "</div>";
	}
	
	function executeAdd() {
		if(! $this->templateExists()) {
			$this->session->error($this->_("MediaLibrary template missing. You may need to install/re-install MediaLibrary module."));
			$this->session->redirect($this->page->url);
		}
		$frm = $this->modules->get("InputfieldForm");
		$frm->attr('id+name', 'AddMediaLibraryForm');
		$frm->attr('action', $this->page->url . "add");
		$frm->attr('method', "POST");
		$frm->title = $this->_("Add Media Library");
		
		$f = $this->modules->get('InputfieldPageListSelect');
		$f->attr('id+name', 'MediaLibraryParent');
		$f->title = $this->_("Parent Page");
		$f->required = true;
		$frm->append($f);
		
		$f = $this->modules->get('InputfieldText');
		if($this->languages) {
			$f->useLanguages = true;
		}
		$f->attr('id+name', 'MediaLibraryTitle');
		$f->title = $this->_("Title");
		$f->required = true;
		$frm->append($f);
		
		$f = $this->modules->get("InputfieldSubmit");
		$f->attr('id+name', 'AddMediaLibrarySubmit');
		$f->attr('value', $this->_("Save"));
		$frm->append($f);
		
		if( $this->input->post->AddMediaLibrarySubmit ) {
			$frm->processInput($this->input->post);
			
			if($frm->getErrors()) {
				$this->session->message("Errors found!");
				$out = $frm->render();
			} else {
				$pagetitle = $frm->get("MediaLibraryTitle")->value;
				//$pagename = $this->sanitizer->pageName($pagetitle, true);
				$parent = $frm->get("MediaLibraryParent")->value;
				
				$p = new Page();
				$p->template = $this->templates->get("MediaLibrary");
				//$p->name = $pagename;
				$p->title = $pagetitle;
				$p->parent = $parent;
				$p->save();

				$this->session->message($this->_("Media page {$pagetitle} created"));
				$this->session->redirect($this->page->url);
			}
		} else {
			if(! $frm->get("MediaLibraryParent")->value) {
				$frm->get("MediaLibraryParent")->set('value', $this->config->rootPageID);
			}
			
			$out = $frm->render();
		}
		
		return $out;
	}
	
	protected function templateExists() {
		if($this->templates->get("MediaLibrary")) return true;
		return false;
	}
	
	public function ___install() {
		$admin = $this->pages->get($this->config->adminRootPageID);
		$pg = $admin->child("name=media");
		if( ! $pg instanceof NullPage ) {
			throw new WireException($this->_("Already a media page present under admin, cancelling installation"));
		}
		$pg = new Page();
		$pg->template = 'admin';
		$pg->name = "media";
		$pg->parent = $admin;
		$pg->title = "Media";
		$pg->save();
		$pg->process = $this->className();
		$pg->addStatus(Page::statusLocked);
		$pg->save();
	}

	public function ___uninstall() {
		$admin = $this->pages->get($this->config->adminRootPageID);
		$pg = $admin->child("name=media");
		if(! $pg instanceof NullPage) {
			$pg->removeStatus(Page::statusLocked);
			$pg->delete();
		}
	}
}

